# Generated by Django 4.1 on 2022-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('music', '0001_initial'), ('music', '0002_song_artist_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
