# Generated by Django 4.1 on 2022-10-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
